[package]
name = "exar-db"
version = "0.1.0"
authors = ["Bruno Filippone <bruno.filippone@b-fil.com>"]

[dependencies]
exar = { version = "0.1", path = "../exar-core" }
exar-net = { version = "0.1", path = "../exar-net" }
exar-client = { version = "0.1", path = "../exar-client" }
exar-server = { version = "0.1", path = "../exar-server" }
stopwatch = "0.0.6"
toml-config = "0.2"
rustc-serialize = "0.3"

[profile.release]
debug = true
opt-level = 3
