[database]
logs_path = "/Users/bruno.filippone/Downloads"
num_scanners = 2
routing_strategy = "Random"
[database.collections.test]
num_scanners = 3
routing_strategy = "RoundRobin"
[server]
host = "127.0.0.1"
port = 38580
username = "admin"
password = "secret"
