[database]
logs_path = "/Users/bruno.filippone/Downloads"
scanners = 2
routing_strategy = "Random"
scanners_sleep_ms = 10
# [database.collections.test]
# scanners = 3
# routing_strategy = "RoundRobin"
# scanners_sleep_ms = 5
[server]
host = "127.0.0.1"
port = 38580
username = "admin"
password = "secret"
