// Generated by typings
// Source: https://raw.githubusercontent.com/aurelia/polyfills/e97d36f958436057ff277c00ce58a0edf42adfed/dist/aurelia-polyfills.d.ts
declare module 'aurelia-polyfills' {
  import {
    PLATFORM
  } from 'aurelia-pal';
}