// Generated by typings
// Source: https://raw.githubusercontent.com/aurelia/pal-browser/ce3451eeeb2feb2c62ec30ec3f6a0122b4209282/dist/aurelia-pal-browser.d.ts
declare module 'aurelia-pal-browser' {
  import {
    initializePAL
  } from 'aurelia-pal';
  
  /**
  * Initializes the PAL with the Browser-targeted implementation.
  */
  export function initialize(): void;
}