// Generated by typings
// Source: https://raw.githubusercontent.com/aurelia/templating-binding/f90d1082b0aa3be71c23e26c1e152b22593a15b5/dist/aurelia-templating-binding.d.ts
declare module 'aurelia-templating-binding' {
  import {BindingLanguage} from 'aurelia-templating';
  
  /**
   * Aurelia's pluggable command syntax.
   */
  export class SyntaxInterpreter {
  }
  
  /**
   * An implementation of Aurelia's binding language
   */
  export class TemplatingBindingLanguage extends BindingLanguage {
  }
}