// Generated by typings
// Source: https://raw.githubusercontent.com/aurelia/typings/master/dist/aurelia-protractor.d.ts
declare module protractor {
  interface IBrowser extends protractor.Protractor {
    loadAndWaitForAureliaPage(url: string): protractor.Protractor;
    waitForRouterComplete();
  }

  interface IProtractorLocatorStrategy {
    valueBind(bindTarget: string): webdriver.Locator;
  }
}
